# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
      inputs:
        version:
          description: 'Version tag (e.g. v1.0.0)'
          required: true
          default: ''

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install Clang
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/setup-clang@ef434b41eb33a70396fb336b1bae39c76d740c3d
      uses: egor-tensin/setup-clang@v1
      with:
        version: 17
        # Set up cc/clang/c++/clang++ executables
        cc: 1

    - name: Setup libbpf headers and libcapstone
      run: |
        sudo apt-get install -y libbpf-dev build-essential xz-utils sudo
        chmod +x ./install-libcapstone.sh
        ./install-libcapstone.sh

    - name: Fetch go dependencies
      run: go mod tidy

    - name: Build eBPF objects
      run: go generate .

    - name: Build
      run: go build -ldflags "-w -s" -o tracer

    - name: Create a release and upload artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: "tracer"
        body: |
          tracer-${{ github.event.inputs.version }}:
            Download on a master node running kube-apiserver. You can specify the host and port of the hub to send the events to it. In any case, it will write all the events to stdout.
        tag: ${{ github.event.inputs.version }}
          

    
